### PR TITLE
Improve symmetry of `bank.parse(bank.format(resource))`.

### PR DESCRIPTION
**Pull request by ioquatix**
Improve handling of separator and delimiter in money formats which don't
follow the internal conventions of BigDecimal.

### CODE REVIEW

**Comment by rainerborene** [comment]
I made a patch that implements a test for this pull request and also `BRL` currency support. It does not pass yet. :bomb:
```diff
diff --git a/lib/latinum/currencies/global.rb b/lib/latinum/currencies/global.rb
index 258d0f4..e6d695c 100644
--- a/lib/latinum/currencies/global.rb
+++ b/lib/latinum/currencies/global.rb
@@ -57,7 +57,7 @@
 			:description => 'Australian Dollar',
 			:formatter => Formatters::DecimalCurrencyFormatter,
 		}
-		
+
 		# @name Global[:USD]
 		# @attribute [Hash] The United States Dollar configuration.
 		Global[:USD] = {
@@ -99,5 +99,17 @@
 			:description => 'Bitcoin',
 			:formatter => Formatters::DecimalCurrencyFormatter
 		}
+		
+		# @name Global[:BRL]
+		# @attribute [Hash] The Brazilian Real configuration.
+		Global[:BRL] = {
+			:precision => 2,
+			:symbol => 'R$',
+			:name => 'BRL',
+			:description => 'Brazilian Real',
+			:formatter => Formatters::DecimalCurrencyFormatter,
+			:delimeter => '.',
+			:separator => ','
+		}
 	end
 end
diff --git a/spec/latinum/bank_spec.rb b/spec/latinum/bank_spec.rb
index 50f4064..95de801 100644
--- a/spec/latinum/bank_spec.rb
+++ b/spec/latinum/bank_spec.rb
@@ -89,4 +89,11 @@
 	it "should fail to parse unknown resource" do
 		expect{@bank.parse("B5")}.to raise_error(ArgumentError)
 	end
+
+	it "should test symmetry of parse and format methods" do
+		resource = Latinum::Resource.new(9.90, "BRL")
+		formatted = @bank.format(resource)
+		expect(formatted).to be == "R$9,90 BRL"
+		expect(@bank.parse(formatted)).to be == resource
+	end
 end
```

**Comment by ioquatix** [comment]
Awesome, I'll take a look tonight.

**Comment by ioquatix** [comment]
Okay, it was a typo, this is now fixed, I'll make a release today.

**Comment by ioquatix** [comment]
Released in `v1.7.1`.

**Comment by rainerborene** [comment]
@ioquatix You rock!

**Pull request merged**
